version: '3'
services:
  backend:
    image: dounty/backend:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: dounty-2025
      DB_USER: dounty-2025
      DB_PASSWORD: dounty-2025
      DATABASE_URL: postgresql://dounty-2025:dounty-2025@db:5432/dounty-2025
    depends_on:
      db:
        condition: service_healthy

  migration:
    image: dounty/migration:latest
    environment:
      DATABASE_URL: postgres://dounty-2025:dounty-2025@db:5432/dounty-2025
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: dounty-2025
      POSTGRES_USER: dounty-2025
      POSTGRES_PASSWORD: dounty-2025
    volumes:
      - './storage/db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 60s
      retries: 10
