# https://www.anchor-lang.com/docs/publishing-source
# https://solana.stackexchange.com/questions/1648/error-no-such-file-or-directory-os-error-2-error-from-anchor-test
[toolchain]
anchor_version = "0.30.1"
solana_version = "2.1.8"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bounty_factory = "HvZ9DweFNYWqV4WNf83cCWogUXmabZHsDNT29DaRUXvm"

[programs.devnet]
bounty_factory = "HvZ9DweFNYWqV4WNf83cCWogUXmabZHsDNT29DaRUXvm"

[registry]
url = "https://api.apr.dev"

# [provider]
# cluster = "Localnet"
# wallet = "~/.config/solana/id.json"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
